### ISSUE TITLE
`bug` doesn't exist in M1i

### ISSUE THREAD

**Issue by cflewis** [unisonweb/unisonweb-org#123]
It looks like `bug()` isn't in ucm M1i, so the [testing docs](https://www.unisonweb.org/docs/testing/) don't work :disappointed: 

```
❯ ucm --version
ucm version: release/M1i

[hack hack use the brokenReverse code]

❯ ucm

   _____     _             
  |  |  |___|_|___ ___ ___ 
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|
  
  Welcome to Unison!
  
  I'm currently watching for changes to .u files under ~
  
  Type help to get help. 😎

.> 

  I'm not sure what bug means at line 18, columns 5-8
  
     18 |     bug ("Not equal!", expected, actual)
  
  Whatever it is, it has a type that conforms to (base.Text, [base.Nat], [base.Nat]) -> base.Boolean.
```

**Comment by anovstrup** [comment]
@cflewis `bug` is in the base library. Have you pulled it with `pull https://github.com/unisonweb/base .base`? If so, what output does `find .base.bug` give you?

**Comment by cflewis** [comment]
@anovstrup : `find .base.bug` with my current install didn't find anything:

```
.> find .base.bug

  😶
  
  No results. Check your spelling, or try using tab completion to supply command arguments.
```
So I tried the pull, but it crashes me back to my command line :sob: 

```
.> pull https://github.com/unisonweb/base .base
⚙  git clone --quiet --depth 1 'https://github.com/unisonweb/base' /home/cflewis/.cache/unisonlanguage/gitfiles/q0rume4r1p1lc5tut0gcbbcvndjgr8ai0qst6ej9bdjr1vcgmtueo0103oi4kt4tr0m1vok5sbkk91g1qcr2og9pit3rp8ceeq752r8/HEAD
⚙  git -C /home/cflewis/.cache/unisonlanguage/gitfiles/q0rume4r1p1lc5tut0gcbbcvndjgr8ai0qst6ej9bdjr1vcgmtueo0103oi4kt4tr0m1vok5sbkk91g1qcr2og9pit3rp8ceeq752r8/HEAD rev-parse --git-dir
.git
ucm: Maybe.fromJust: Nothing
```

**Comment by anovstrup** [comment]
That error [looks familiar](https://github.com/unisonweb/unison/issues/1303). /cc @aryairani

**Comment by cflewis** [comment]
Assuming that we do get the pull working, I think there is a probable disconnect between "I got the latest alpha build" and "I got the latest base library". I assumed the latest build would mean I had the latest `.base` library, not that I'd need to pull it.

Perhaps this could be documented at the head of the docs, or `ucm` itself should prompt that `.base` is out of date for a particular build?

**Comment by anovstrup** [comment]
If you upgraded to M1i from an earlier version, `ucm` is using your existing codebase from that earlier version (including whatever was in `.base`, until you pull more recent updates). 

I agree that this could use better documentation, especially since the relationship between `ucm` and the base library is very different from that between most language runtimes and their standard libraries. With Unison, the base library can evolve (mostly) separately, and because it's an append-only Unison codebase like any other, the only concern with having an old version is that you may be missing definitions you expect to find there (as you did!) — code that relies on stale definitions, on the other hand, will continue to function without any change when you pull the new library (although you may _want_ to patch code to use newer definitions).

**Comment by cflewis** [comment]
Yeah, perhaps this will all resolve itself as things go.

Now you have planted a seed in my mind: is there a way to ask `ucm` what version of a library it's using, and is there a way to know that one hash is lower than another? If you are writing a doc about some new feature that absolutely relies on a version or higher of a library, you could write "If `version.compare .base [new hash]` says the version is lower, you'll need to update your base library to at least [new hash] with `pull ...`" (for the base library obviously).

Kinda like Go where they label the minimum version to find a function from the stdlib?

**Comment by cflewis** [comment]
I'm happy if you want to mark this resolved, it's a transient issue that might require bigger thinking, but the immediate problem is that I was Holding It Wrong.

**Comment by pchiusano** [comment]
I'm going to close, but yeah I think there's some bigger thinking to do here. We should probably just version the site so past versions are available too. Perhaps  `/docs` redirects to the latest which is at `/M1j/docs`, etc.
