### ISSUE TITLE
Document Transcript Usage

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unisonweb-org#271]
**Summary: we should document what transcripts are and how to use them on the website.**

Transcripts are a really neat feature of Unison. They can/could be used for:

- Bug reporting
- Testing
- Documentation/tutorials/literate programming

If you run `ucm --help transcript` or `ucm --help transcript.fork` you get a bit of help about the `transcript` command, but currently there doesn't seem to be any docs about transcripts on the website.

We have some examples of transcripts [here](https://github.com/unisonweb/unison/tree/trunk/unison-src/transcripts) that could be used as examples to assist in documenting how transcripts can be used. But transcripts could probably also be used in lots of other creative ways, and I'd love for people to explore that space.

**Comment by aryairani** [comment]
Here is the original "example transcript":
https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts/hello.md
https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts/hello.output.md

**Comment by ceedubs** [comment]
Resolved by #281. Thanks @rlmark!
