### ISSUE TITLE
Doc issue: wrong url for pulling base

### ISSUE THREAD

**Issue by jemma-nelson** [unisonweb/unisonweb-org#326]
On this page: https://www.unison-lang.org/learn/ucm-commands/pull/

It recommends the command `pull unison.public.base.releases.latest lib.base`, which yields:

```
.> pull unison.public.base.releases.latest lib.base

  Downloaded 0 entities.

  ❗️

  The server didn't find anything at
  unison.public.base.releases.latest
```

I believe this should instead be `pull unison.public.base.latest lib.base`.

**Comment by rlmark** [comment]
Thanks for reporting @jemma-nelson! This change has been deployed!
