### ISSUE TITLE
`ucm` fenced code blocks should get a block type of `ucm`, not `code`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unisonweb-org#36]
![image](https://user-images.githubusercontent.com/11074/69659026-5bfb2a00-104b-11ea-95e7-dbe098341cbc.png)

For instance [here](https://deploy-preview-35--unisonweb-org.netlify.com/docs/refactoring)

**Comment by brianfryer** [comment]
@pchiusano Gotta PR for this here: https://github.com/unisonweb/unisonweb-org/pull/41

Deploy preview: https://5dee7edd3e6fde00097c50a7--unisonweb-org.netlify.com/docs/refactoring

> ![image](https://user-images.githubusercontent.com/1923767/70456723-4dae0480-1a74-11ea-9854-c84b93716853.png)

**Comment by pchiusano** [comment]
Nice, thanks @brianfryer
