### ISSUE TITLE
Language reference page on types omits user-defined types

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/unisonweb-org#42]
The [page covering Unison's type system](https://www.unisonweb.org/docs/language-reference/types) conspicuously omits any discussion of user-defined types, which are covered in [their own page](https://www.unisonweb.org/docs/language-reference/type-declarations) titled in the sidebar as "Type Declarations".  IMO, there should be at least some mention of user-defined types on the "Types" page, with links back to the other page for details. Without this, I had a hard time re-finding the section on record types.

**Comment by anovstrup** [comment]
I wouldn't mind putting together a PR, as long as the team is on board with this suggestion.

**Comment by pchiusano** [comment]
@anovstrup sure that sounds like a good PR. Maybe something like this after the first sentence: "This section describes informally the structure of types in Unison. Also see `<link>` for information on how declare new user-defined types." and maybe do the same elsewhere in the doc. Not sure, go with what you think seems reasonable.

Something that is a little confusing is that there is a distinction between "types" (the things that can appear in a function's signature, and the subject of the current types page) and "type declarations" (which are things that introduce new symbols that can be used in these signatures). People sometimes say "type" to refer to both these concepts.

If you can come up with a way to make this clear in the PR and hopefully point people in the right direction that would be nice :)
